##################################################
# CsiPdfUtils_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from CsiPdfUtils_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding
from CsiPdfUtils import PdfMerger

class PdfMerge_Service(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?><wsdl:definitions name=\"CsiPdfUtils\" targetNamespace=\"http://PdfUtils.csi.org/merge/\" xmlns:csi=\"http://PdfUtils.csi.org/merge/\" xmlns:pdfMerge=\"http://PdfUtils.csi.org/merge/PdfMerge.xsd\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">



   <wsdl:message name=\"PdfMergeRequest\">
      <wsdl:part element=\"pdfMerge:PdfMergeRequest\" name=\"PdfMergeRequest\"/>
   </wsdl:message>

   <wsdl:message name=\"PdfMergeResponse\">
      <wsdl:part element=\"pdfMerge:PdfMergeResponse\" name=\"PdfMergeResponse\"/>
    </wsdl:message>

   <wsdl:portType name=\"PdfMerge_PortType\">
      <wsdl:operation name=\"merge2Pdfs\">
         <wsdl:input message=\"csi:PdfMergeRequest\"/>
         <wsdl:output message=\"csi:PdfMergeResponse\"/>
      </wsdl:operation>
   </wsdl:portType>

   <wsdl:binding name=\"PdfMerge_Binding\" type=\"csi:PdfMerge_PortType\">
      <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
      <wsdl:operation name=\"merge2Pdfs\">
        <soap:operation soapAction=\"http://PdfUtils.csi.org/merge2Pdfs\"/>
        <wsdl:input>
          <soap:body use=\"literal\"/>
        </wsdl:input>
        <wsdl:output>
          <soap:body use=\"literal\"/>
        </wsdl:output>
      </wsdl:operation>
    </wsdl:binding>

   <wsdl:service name=\"PdfMerge_Service\">
      <wsdl:documentation>WSDL File for HelloService</wsdl:documentation>
      <wsdl:port binding=\"csi:PdfMerge_Binding\" name=\"PdfMerge_Port\">
         <soap:address location=\"http://172.28.105.55:8080\"/>
      </wsdl:port>
   </wsdl:service>
<xsd:schema targetNamespace=\"http://PdfUtils.csi.org/merge/PdfMerge.xsd\" xmlns=\"http://PdfUtils.csi.org/merge/PdfMerge.xsd\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi1=\"http://PdfUtils.csi.org/types.xsd\">

	<xsd:import namespace=\"http://PdfUtils.csi.org/types.xsd\" schemaLocation=\"commonTypes.xsd\"/>

	<xsd:complexType name=\"PdfMergeRequest\">
		<xsd:sequence>
			<xsd:element name=\"operacio\" type=\"xsd:string\"/>
			<xsd:element name=\"llistaPdfs_b64\" type=\"xsi1:llistaPdfs_b64\"/>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name=\"PdfMergeResponse\">
		<xsd:sequence>
			<xsd:element name=\"error\" type=\"xsi1:llistaErrors\"/>
			<xsd:element name=\"outputPdf\" type=\"xsd:string\"/>
		</xsd:sequence>
	</xsd:complexType>


</xsd:schema></wsdl:definitions>"""

    def __init__(self, post='', **kw):
        ServiceSOAPBinding.__init__(self, post)

    #Función que implementa el comportamiento de fusión de pdfs.
    def soap_merge2Pdfs(self, ps):
        self.request = ps.Parse(PdfMergeRequest.typecode)
        response =  PdfMergeResponse()
        response._error = ns1.llistaErrors_Def("llistaErrors")
        response._outputPdf = ""
        listaErrors = []
        if self.request._operacio == "merge":
            pdfMerger = PdfMerger.PdfMerger()
            listaPdfs = self.request._llistaPdfs_b64._pdf_b64
            for pdf in listaPdfs:
                pdfMerger.add_pdf_b64(pdf)
            response._outputPdf = pdfMerger.write_output_b64()
        else:
            errorItem = ns1.errorItem_Def("errorItem")
            errorItem._codi = 1
            errorItem._descripcio = "La operacio no es correcte"
            listaErrors.append(errorItem)
            #lista = [ errorItem ]
        response._error._llistaErrors =  listaErrors
        return response

    soapAction['http://PdfUtils.csi.org/merge2Pdfs'] = 'soap_merge2Pdfs'
    root[(PdfMergeRequest.typecode.nspname,PdfMergeRequest.typecode.pname)] = 'soap_merge2Pdfs'
